Update blue-main.yml

diff --git a/.github/workflows/blue-main.yml b/.github/workflows/blue-main.yml
--- a/.github/workflows/blue-main.yml
+++ b/.github/workflows/blue-main.yml
@@ -145,12 +145,7 @@ jobs:
         ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/lemp-setup.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
-    - name: Run cloudflare-dns.sh on the VM
-      run: |
-        echo "Running cloudflare-dns.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
-        echo "Script executed successfully."
-    
+   
     - name: Run wordpress-install.sh on the VM
       run: |
         echo "Running wordpress-install.sh on VM..."
@@ -202,7 +197,13 @@ jobs:
         echo "Terminating EC2 instance: $INSTANCE_ID"
         aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
         aws ec2 wait instance-terminated --instance-ids "$INSTANCE_ID"
-        echo "EC2 instance $INSTANCE_ID terminated successfully."          
+        echo "EC2 instance $INSTANCE_ID terminated successfully."    
+
+    - name: Run cloudflare-dns.sh on the VM
+      run: |
+        echo "Running cloudflare-dns.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
 
     - name: Run certbot-ssl-install.sh on the VM
       run: |
