Update blue-main.yml

diff --git a/.github/workflows/blue-main.yml b/.github/workflows/blue-main.yml
--- a/.github/workflows/blue-main.yml
+++ b/.github/workflows/blue-main.yml
@@ -188,23 +188,23 @@ jobs:
         ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/dump-restore.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
-    - name: Run certbot-ssl-install.sh on the VM
-      run: |
-        echo "Running certbot-ssl-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
-        echo "Script executed successfully."
+ #   - name: Run certbot-ssl-install.sh on the VM
+  #    run: |
+   #     echo "Running certbot-ssl-install.sh on VM..."
+   #     ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
+   #     echo "Script executed successfully."
 
-    - name: Run test-dump-restore.sh on the VM
-      run: |
-        echo "Running certbot-ssl-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/test-dump-restore.sh || { echo "Script failed"; exit 1; }'
-        echo "Script executed successfully."
+   # - name: Run test-dump-restore.sh on the VM
+   #   run: |
+   #     echo "Running certbot-ssl-install.sh on VM..."
+   #     ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/test-dump-restore.sh || { echo "Script failed"; exit 1; }'
+   #     echo "Script executed successfully."
 
-    - name: Run status-check.sh on the VM
-      run: |
-        echo "Running certbot-ssl-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/status-check.sh || { echo "Script failed"; exit 1; }'
-        echo "Script executed successfully."
+    #- name: Run status-check.sh on the VM
+    #  run: |
+    #    echo "Running certbot-ssl-install.sh on VM..."
+     #   ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/status-check.sh || { echo "Script failed"; exit 1; }'
+     #   echo "Script executed successfully."
 
         
         
