Update dev-workflow.yml
s3fs-mount.sh and copy-wordpress-content.sh added

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -76,9 +76,9 @@ jobs:
         sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./dev/wordpress-install.sh
         cat ./dev/wordpress-install.sh  # Print file contents to confirm the edits
         
-        echo "Editing persistent storage variables in storage-setup.sh..."
-        sed -i "s|STORAGE_URL|$S_STORAGE_URL|g" ./dev/storage-setup.sh
-        cat ./dev/storage-setup.sh  # Print file contents to confirm the edits
+        echo "Editing persistent storage variables in s3fs-mount.sh..."
+        sed -i "s|STORAGE_URL|$S_STORAGE_URL|g" ./dev/s3fs-mount.sh
+        cat ./dev/s3fs-mount.sh  # Print file contents to confirm the edits
         
     - name: Copy files to Development VM
       env:
@@ -158,7 +158,17 @@ jobs:
         ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/wordpress-install.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
-    - name: Run storage-setup.sh on the VM
+    - name: Run s3fs-mount.sh on the VM
+      env:
+          ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+          SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+          SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+          echo "Running s3fs-mount.sh on VM..."
+          ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/s3fs-mount.sh || { echo "Script failed"; exit 1; }'
+          echo "Script executed successfully." 
+    
+    - name: Run copy-wordpress-content.sh on the VM
       uses: nick-invision/retry@v2
       env:
         ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
@@ -167,12 +177,10 @@ jobs:
       with:
         timeout_minutes: 10
         max_attempts: 3
-        retry_wait_seconds: 30
-        warning_on_retry: true
         command: |
-          echo "Running storage-setup.sh on VM..."
-          ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/storage-setup.sh || { echo "Script failed"; exit 1; }'
-          echo "Script executed successfully."
+          echo "Running copy-wordpress-content.sh on VM..."
+          ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/copy-wordpress-content.sh || { echo "Script failed"; exit 1; }'
+          echo "Script executed successfully." 
           
     - name: Run certbot-ssl-install.sh on the VM
       env:
