Update dev-workflow.yml
- name: Run lemp-setup.sh on the VM
- name: Run cloudflare-dns.sh on the VM
- name: Run wordpress-install.sh on the VM
- name: Run certbot-ssl-install.sh on the VM
added

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -1,4 +1,4 @@
-name: Test and Deploy Bash Script.
+name: Development
 
 on:
   push:
@@ -45,30 +45,30 @@ jobs:
       run: |
         echo "Editing Cloudflare variables in lemp-setup.sh..."
         sed -i "s/S_DOMAIN/$DOMAIN/g" ./lemp-setup.sh
-        sed -i "s/S_ELASTIC_IP/$ELASTIC_IP/g" ./lemp-setup.sh
-        sed -i "s/S_CF_API/$SECRET_CF_API/g" ./lemp-setup.sh
-        sed -i "s/S_CF_ZONE_ID/$CF_ZONE_ID/g" ./lemp-setup.sh
-        cat ./lemp-setup.sh  # Print file contents to confirm the edits
+        sed -i "s/S_ELASTIC_IP/$ELASTIC_IP/g" ./dev/lemp-setup.sh
+        sed -i "s/S_CF_API/$SECRET_CF_API/g" ./dev/lemp-setup.sh
+        sed -i "s/S_CF_ZONE_ID/$CF_ZONE_ID/g" ./dev/lemp-setup.sh
+        cat ./dev/lemp-setup.sh  # Print file contents to confirm the edits
         
         echo "Editing Cloudflare variables in certbot-ssl-install.sh..."
-        sed -i "s/S_EMAIL/$EMAIL/g" ./certbot-ssl-install.sh
-        sed -i "s/S_DOMAIN/$DOMAIN/g" ./certbot-ssl-install.sh
-        cat ./certbot-ssl-install.sh  # Print file contents to confirm the edits
+        sed -i "s/S_EMAIL/$EMAIL/g" ./dev/certbot-ssl-install.sh
+        sed -i "s/S_DOMAIN/$DOMAIN/g" ./dev/certbot-ssl-install.sh
+        cat ./dev/certbot-ssl-install.sh  # Print file contents to confirm the edits
 
         echo "Editing Cloudflare variables in cloudflare-dns.sh..."
-        sed -i "s/S_DOMAIN/$DOMAIN/g" ./cloudflare-dns.sh
-        sed -i "s/S_ELASTIC_IP/$ELASTIC_IP/g" ./cloudflare-dns.sh
-        sed -i "s/S_CF_API/$SECRET_CF_API/g" ./cloudflare-dns.sh
-        sed -i "s/S_CF_ZONE_ID/$CF_ZONE_ID/g" ./cloudflare-dns.sh
-        cat ./cloudflare-dns.sh  # Print file contents to confirm the edits
+        sed -i "s/S_DOMAIN/$DOMAIN/g" ./dev/cloudflare-dns.sh
+        sed -i "s/S_ELASTIC_IP/$ELASTIC_IP/g" ./dev/cloudflare-dns.sh
+        sed -i "s/S_CF_API/$SECRET_CF_API/g" ./dev/cloudflare-dns.sh
+        sed -i "s/S_CF_ZONE_ID/$CF_ZONE_ID/g" ./dev/cloudflare-dns.sh
+        cat ./dev/cloudflare-dns.sh  # Print file contents to confirm the edits
 
         echo "Editing MariaDB variables in wordpress-install.sh..."
-        sed -i "s/DB_PASSWORD/$DB_PASSWORD/g" ./wordpress-install.sh
-        sed -i "s/DB_USERNAME/$DB_USERNAME/g" ./wordpress-install.sh
+        sed -i "s/DB_PASSWORD/$DB_PASSWORD/g" ./dev/wordpress-install.sh
+        sed -i "s/DB_USERNAME/$DB_USERNAME/g" ./dev/wordpress-install.sh
 
         echo "Editing persistent storage variables in wordpress-install.sh..."
-        sed -i "s|STORAGE_URL|$S_STORAGE_URL|g" ./wordpress-install.sh
-        cat ./wordpress-install.sh  # Print file contents to confirm the edits
+        sed -i "s|STORAGE_URL|$S_STORAGE_URL|g" ./dev/wordpress-install.sh
+        cat ./dev/wordpress-install.sh  # Print file contents to confirm the edits
    
     - name: Copy files to Development VM
       env:
@@ -89,4 +89,43 @@ jobs:
         echo "Running git-setup.sh on VM..."
         ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/git-setup.sh || { echo "Script failed"; exit 1; }' 
         echo "Script executed successfully."
-      
+
+    - name: Run lemp-setup.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running lemp-setup.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/lemp-setup.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+    - name: Run cloudflare-dns.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running cloudflare-dns.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT$SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+    
+    - name: Run wordpress-install.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running wordpress-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/wordpress-install.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+    - name: Run certbot-ssl-install.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running certbot-ssl-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
