Update dev-workflow.yml
        echo "Editing variables variables in dump-restore.sh..."
        echo "Editing variables variables in test-dump-restore.sh..."
        echo "Editing variables variables in status-check.sh..."
added

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -79,6 +79,25 @@ jobs:
         echo "Editing persistent storage variables in s3fs-mount.sh..."
         sed -i "s|STORAGE_URL|$S_STORAGE_URL|g" ./dev/s3fs-mount.sh
         cat ./dev/s3fs-mount.sh  # Print file contents to confirm the edits
+
+        echo "Editing variables variables in dump-restore.sh..."
+        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' ./dev/dump-restore.sh
+        sed -i 's/DB_USERNAME/${{ secrets.DB_USERNAME }}/g' ./dev/dump-restore.sh
+        sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./dev/dump-restore.sh
+        cat ./dev/dump-restore.sh  # Print file contents to confirm the edits
+
+        echo "Editing variables variables in status-check.sh..."
+        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' ./qa/status-check.sh
+        sed -i 's/DB_USERNAME/${{ secrets.DB_USERNAME }}/g' ./qa/status-check.sh
+        sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./qa/status-check.sh
+        sed -i 's/S_DOMAIN/${{ secrets.DOMAIN }}/g' ./qa/status-check.sh
+        cat ./qa/status-check.sh  # Print file contents to confirm the edits
+
+        echo "Editing variables variables in test-dump-restore.sh..."
+        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' ./qa/test-dump-restore.sh
+        sed -i 's/DB_USERNAME/${{ secrets.DB_USERNAME }}/g' ./qa/test-dump-restore.sh
+        sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./qa/test-dump-restore.sh
+        cat ./qa/test-dump-restore.sh  # Print file contents to confirm the edits
         
     - name: Copy files to Development VM
       env:
@@ -182,6 +201,16 @@ jobs:
           ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/copy-wordpress-content.sh || { echo "Script failed"; exit 1; }'
           echo "Script executed successfully." 
           
+    - name: Run dump-restore.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running dump-restore.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $$SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/dump-restore.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+    
     - name: Run certbot-ssl-install.sh on the VM
       env:
         ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
@@ -190,4 +219,24 @@ jobs:
       run: |
         echo "Running certbot-ssl-install.sh on VM..."
         ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+    - name: Run test-dump-restore.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running certbot-ssl-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/test-dump-restore.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+    - name: Run status-check.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      run: |
+        echo "Running certbot-ssl-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/status-check.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
