Update dev-workflow.yml

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -165,7 +165,7 @@ jobs:
     - name: Run zabbix-agent.sh on the VM
       run: |
         echo "Running zabbix-agent.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/zabbix/zabbix-agent.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/zabbix/zabbix-agent.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
     - name: Run lemp-setup.sh on the VM
