Update dev-workflow.yml

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -108,6 +108,11 @@ jobs:
         sed -i "s/DOMAIN/$DOMAIN/g" ./qa/dump-backup.sh
         cat ./qa/dump-backup.sh  # Print file contents to confirm the edits
 
+        echo "Editing variables variables in zabbix-agent.sh..."
+        sed -i 's/S_ZABBIX_IP/${{ secrets.ZABBIX_IP }}/g' ./zabbix/zabbix-agent.sh
+        sed -i 's/CLIENT_HOSTNAME/${{ secrets.HOSTNAME }}/g' ./zabbix/zabbix-agent.sh
+        cat ./zabbix/zabbix-agent.sh  # Print file contents to confirm the edits
+
         
     - name: Copy files to Development VM
       env:
@@ -230,6 +235,12 @@ jobs:
       run: |
         echo "Running certbot-ssl-install.sh on VM..."
         ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+    - name: Run zabbix-agent.sh on the VM
+      run: |
+        echo "Running certbot-ssl-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/zabbix/zabbix-agent.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
     - name: Run test-dump-restore.sh on the VM
