Update dev-workflow.yml
dev-workflow adjusted to the last repo update

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -1,14 +1,17 @@
 name: Development
 
 on:
-  push:
-    branches:
-      - dev
+  workflow_run:
+    workflows:
+      - GreenEnv Deploy CloudFormation Stack
+    types:
+      - completed
   
 jobs:
   deploy_to_dev:
     runs-on: ubuntu-latest
-    environment: Development  # Specify the environment here
+    timeout-minutes: 120
+    environment: Development  
 
     steps:
     - name: Checkout code
@@ -26,7 +29,7 @@ jobs:
         SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
         SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
       run: |
-        echo "Testing SSH connection..."
+        echo "Testing SSH connection to $ELASTIC_IP as $SSH_USERNAME on port $SSH_PORT..."
         ssh -vvv -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP "echo 'SSH Connection Successful'"
 
     - name: Edit CF Variables
@@ -97,7 +100,7 @@ jobs:
         SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
       run: |
         echo "Running lemp-setup.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/lemp-setup.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/lemp-setup.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
     - name: Run cloudflare-dns.sh on the VM
@@ -107,7 +110,7 @@ jobs:
         SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
       run: |
         echo "Running cloudflare-dns.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT$SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT$SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
     
     - name: Run wordpress-install.sh on the VM
@@ -117,9 +120,23 @@ jobs:
         SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
       run: |
         echo "Running wordpress-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/wordpress-install.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/wordpress-install.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
+    - name: Run storage-setup.sh on the VM
+      env:
+        ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME_DEV }}
+        SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
+      uses: nick-invision/retry@v2
+      with:
+        timeout_minutes: 10
+        max_attempts: 3
+        command: |
+          echo "Running certbot-ssl-install.sh on VM..."
+          ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/storage-setup.sh || { echo "Script failed"; exit 1; }'
+          echo "Script executed successfully."
+          
     - name: Run certbot-ssl-install.sh on the VM
       env:
         ELASTIC_IP: ${{ secrets.ELASTIC_IP_DEV }}
@@ -127,5 +144,5 @@ jobs:
         SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
       run: |
         echo "Running certbot-ssl-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
