Update dev-workflow.yml
spare $

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -208,7 +208,7 @@ jobs:
         SSH_PORT: ${{ secrets.SSH_PORT_DEV }}
       run: |
         echo "Running dump-restore.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p $$SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/dump-restore.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$ELASTIC_IP 'sudo bash /home/ubuntu/EPA-Wordpress-project/dev/dump-restore.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
     
     - name: Run certbot-ssl-install.sh on the VM
