Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -68,13 +68,26 @@ jobs:
         sed -i 's|STORAGE_URL|'"${{ secrets.S_STORAGE_URL }}"'|g' ./s3fs-mount.sh
         cat ./s3fs-mount.sh  # Print file contents to confirm the edits
 
-        echo "Editing persistent storage variables in dump-restore.sh..."
+        echo "Editing variables variables in dump-restore.sh..."
         sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' ./dump-restore.sh
         sed -i 's/DB_USERNAME/${{ secrets.DB_USERNAME }}/g' ./dump-restore.sh
         sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./dump-restore.sh
         cat ./dump-restore.sh  # Print file contents to confirm the edits
 
+        echo "Editing variables variables in status-check.sh..."
+        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' ./qa/status-check.sh
+        sed -i 's/DB_USERNAME/${{ secrets.DB_USERNAME }}/g' ./qa/status-check.sh
+        sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./qa/status-check.sh
+        sed -i 's/S_DOMAIN/${{ secrets.DOMAIN }}/g' ./qa/status-check.sh
+        cat ./qa/status-check.sh  # Print file contents to confirm the edits
+
+        echo "Editing variables variables in test-dump-restore.sh..."
+        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' ./qa/test-dump-restore.sh
+        sed -i 's/DB_USERNAME/${{ secrets.DB_USERNAME }}/g' ./qa/test-dump-restore.sh
+        sed -i 's/RDS_ENDPOINT/${{ secrets.RDS_ENDPOINT }}/g' ./qa/test-dump-restore.sh
+        cat ./qa/test-dump-restore.sh  # Print file contents to confirm the edits
         
+     
     - name: Copy files to VM
       run: |
         echo "Starting file transfer process..."
@@ -171,4 +184,18 @@ jobs:
         echo "Running certbot-ssl-install.sh on VM..."
         ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
+
+    - name: Run test-dump-restore.sh on the VM
+      run: |
+        echo "Running certbot-ssl-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/test-dump-restore.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+    - name: Run status-check.sh on the VM
+      run: |
+        echo "Running certbot-ssl-install.sh on VM..."
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/qa/status-check.sh || { echo "Script failed"; exit 1; }'
+        echo "Script executed successfully."
+
+        
         
